title: swoj tytul
description: nie mam pojecia co ja robie
theme: just-the-docs

url: https://qbona12.github.io/just-the-docs

aux_links:
  Template Repository: https://github.com/qbona12/just-the-docs

